name: Build Libraries
on: [push]
jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
      - name: Setup Go Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Build darwin-amd64 library
        run: GOOS=darwin GOARCH=amd64 LIBSUFFIX=dylib ./build.sh
      - name: Build darwin-amd64 library
        run: GOOS=darwin GOARCH=arm64 LIBSUFFIX=dylib ./build.sh
      - name: Build darwin-universal library
        run: ./universal.sh darwin-universal darwin-amd64 darwin-arm64
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libtailscale-libs
          path: build/
          if-no-files-found: error
