name: Build libtailscale
on: [push]
jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
      - name: Setup Go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Build darwin-amd64 library
        run: GOOS=darwin GOARCH=amd64 LIBSUFFIX=dylib ./build.sh
      - name: Build darwin-arm64 library
        run: GOOS=darwin GOARCH=arm64 LIBSUFFIX=dylib ./build.sh
      - name: Build darwin-universal library
        run: ./universal.sh darwin-universal darwin-amd64 darwin-arm64
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libtailscale-darwin
          path: libs/
          if-no-files-found: error
      - name: Upload archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libtailscale-darwin-archives
          path: archives/
          if-no-files-found: error
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
      - name: Setup Go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Build linux-amd64 library
        run: GOOS=linux GOARCH=amd64 LIBSUFFIX=so ./build.sh
      - name: Install aarch64 toolchain
        run: sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Build linux-arm64 library
        run: CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 LIBSUFFIX=so ./build.sh
      - name: Upload library artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libtailscale-linux
          path: libs/
          if-no-files-found: error
      - name: Upload archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libtailscale-linux-archives
          path: archives/
          if-no-files-found: error
  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #     - name: Setup Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: '>=1.20.1'
  #     - name: Setup Go cache
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           ~/.cache/go-build
  #           ~/go/pkg/mod
  #         key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
  #         restore-keys: |
  #           ${{ runner.os }}-golang-
  #     - name: Build windows-amd64 library
  #       run: .\build.ps1
  #       env:
  #         GOOS: windows
  #         GOARCH: amd64
  #         LIBSUFFIX: dll
  #     - name: Build windows-arm64 library
  #       run: .\build.ps1
  #       env:
  #         GOOS: windows
  #         GOARCH: arm64
  #         LIBSUFFIX: dll
  #     - name: Upload library artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: libtailscale-libs
  #         path: libs/
  #         if-no-files-found: error
  package:
    needs:
    - linux
    - darwin
    runs-on: ubuntu-latest
    steps:
      - name: Download linux libraries
        uses: actions/download-artifact@v3
        with:
          name: libtailscale-linux
          path: libs
      - name: Download darwin libraries
        uses: actions/download-artifact@v3
        with:
          name: libtailscale-darwin
          path: libs
      - name: Download linux archives
        uses: actions/download-artifact@v3
        with:
          name: libtailscale-linux-archives
          path: archives
      - name: Download darwin archives
        uses: actions/download-artifact@v3
        with:
          name: libtailscale-darwin-archives
          path: archives
      - name: Upload library artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libtailscale-all
          path: libs/
          if-no-files-found: error
      - name: Upload archives artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libtailscale-all-archives
          path: archives/
          if-no-files-found: error
